name: ci

env:
  CONFIG_REPO_NAME: app-helmfile
  PR_SOURCE_BRANCH: ${{ github.event.pull_request.head.ref }}
on:
  pull_request:
    types: [labeled]
  push:
    branches: [ "**" ] 

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Unit Tests
        run: |
          echo "Implement unit tests if applicable."
          echo "This stage is a sample placeholder."

  docker-build-push:
    runs-on: ubuntu-latest
    needs: unit-tests
    env:
      VERSION: ${{ github.run_number }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t app .
          docker tag app ameyg/app:$VERSION
          docker push ameyg/app:$VERSION

  promote-to-dev-environment:
    if: ${{ github.event.label.name == 'sandbox'  || github.event.label.name == 'qa' ||  }}
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Set up Git
        run: |
          git config --global user.email "argocd-user@argocd.com"
          git config --global user.name "argocd-user"

      - name: Clone GitOps Config Repo
        run: |
          echo "Cloning config repo $CONFIG_REPO_NAME"
          git clone https://oauth2:${{ secrets.GH_PAT }}@github.com/${{ github.repository_owner }}/$CONFIG_REPO_NAME.git
          cd $CONFIG_REPO_NAME
          
          if [[ "${{ github.event.label.name }}" == "sandbox" ]]; then
            git checkout sandbox

          elif [[ "${{ github.event.label.name }}" == "qa" ]]; then
            git checkout qa
  
          elif [[ "${{ github.event.label.name }}" == "preprod" ]]; then
            git checkout preprod

          elif [[ "${{ github.event.label.name }}" == "qa-test" ]]; then
            BRANCH_NAME="itr-${{PR_SOURCE_BRANCH}}-qa-test"
            git checkout BRANCH_NAME

          elif [[ "${{ github.event.label.name }}" == "sanbox-test" ]]; then
            BRANCH_NAME="itr-${{PR_SOURCE_BRANCH}}-sandbox-test"
            git checkout BRANCH_NAME          
          fi

      - name: Update Image Tag
        run: |
          cd $CONFIG_REPO_NAME
          sed -i "s,tag:.*,tag:\ ${{ github.run_number }}," values.yaml
          cat values.yaml

      - name: Commit and Push Changes
        run: |
          cd $CONFIG_REPO_NAME
          git add .
          git commit -m "Update image tag to ${{ github.run_number }}"
          git push
